### ISSUE TITLE
GPLv2 violation: OOS 11.1.2.2 Kernel sources NOT updated. 

### ISSUE THREAD

**Issue by mcdachpappe** [OnePlusOSS/android_kernel_oneplus_sdm845#8]
Hello,

a certain amount of time has now passed and the sources have still not been released. Another issue was already opened at #7 and was ignored until now.

I would like to point out once again that OnePlus have to comply with the license that comes with the Linux kernel because not releasing the sources is a clear violation of the GPLv2.
A copy of the license is here: https://github.com/torvalds/linux/blob/master/LICENSES/preferred/GPL-2.0

We know that no more updates will be released for this device, so please publish the source code of the last version to put an end to it. While we are at it I still want to thank you for the good support and the great device. I wish you all the best for the future.

For reference:
https://forums.oneplus.com/threads/oneplus-6-6t-android-11-kernel-sources-not-released-gplv2.1490369/#post-23607353

**Comment by He-Is-HaZaRdOuS** [comment]
+1 bump, kindly request up-to-date kernel sources for the 6/6t

**Comment by voidkills** [comment]
+1, bump, please provide us with the latest kernel sources for enchilada, and fajita.

**Comment by youmukonpaku1337** [comment]
+1 bump, please give us the latest kernel sources for both enchilada and fajita.

**Comment by Terminator-J** [comment]
Hear hear!

**Comment by Bush-cat** [comment]
+1 bump, we need the updated sauce to pour over our fajitas and enchiladas, the old one started rotting.

**Comment by umangtayal** [comment]
+1 bump, please release updated kernel sources for enchilada and fajita.

**Comment by mdumair-sk** [comment]
+1, bump, please release the latest kernel sources for 6/6T.

**Comment by radu-v** [comment]
👍 I concur.
Thanks for all the support, but especially since it ended for OP6/T, please comply with GPLv2 and release the latest kernel source code.

**Comment by PhoenixKiller1** [comment]
+1, bump. Please release kernel sources

**Comment by topes1** [comment]
1+ bump, kindly request up-to-date kernel sources for the 6/6t.

**Comment by sjnssns** [comment]
+1 bump, kindly release the latest kernel sources for OP6/6T

**Comment by topes2** [comment]
+1 bump, kindly release the latest kernel sources for OP6/6T. Like come on are you scared?

**Comment by JumbomanXDA** [comment]
Dear OnePlus, plz provide updated sources

**Comment by SevralT** [comment]
GPL......

**Comment by AlessandroGandolfi** [comment]
Please release these damn sources so we can be satisfied, you would legally do your job and both sides would have a happy ending :)

**Comment by SevralT** [comment]
@torvalds They dont want publish linux source code 😂

**Comment by wannaskoo** [comment]
+1, it's really important

**Comment by Alucard-Storm** [comment]
Please provide us updated sources code so we can keep this legendary phone alive

**Comment by bluesaphires** [comment]
+1, dear oneplus please provide us the updated sources!

**Comment by danvilar** [comment]
+1 please update the sources

**Comment by SmarterDonkey** [comment]
+1 please publish updated kernel source code

**Comment by droid-jd** [comment]
C'mon OnePlus. Publish!

**Comment by zclean** [comment]
+1 bump, kindly request up-to-date kernel sources for the 6/6t

**Comment by Spongepoop** [comment]
Kindly request up-to-date kernel sources for the 6/6t

**Comment by fuomag9** [comment]
+1 bump, please comply with the GPL2 License

**Comment by Juuuuulie10** [comment]
+1 please comply with the licence and release proper sources. And please do NOT try to hide any code from public, that's illegal.

**Comment by authorisation** [comment]
+1 Completely agree with everyone here, GPL states code should be public

**Comment by nisuraaa** [comment]
+1 bump, please comply with the GPL2 License

**Comment by Akruidenberg** [comment]
+1

**Comment by ChromevoidGit** [comment]
kindly request up-to-date kernel sources for the 6/6t

**Comment by KaratekHD** [comment]
+1

**Comment by CaldeiraG** [comment]
+1 bump

**Comment by ZehuaMc** [comment]
+1

**Comment by purveshSane** [comment]
+1, bump, please provide us with the latest kernel sources for enchilada, and fajita.

**Comment by bhargav516** [comment]
+1

**Comment by xiangmj** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by kasboi** [comment]
We await

**Comment by kimocoder** [comment]
+1 simple as that

**Comment by robcreel** [comment]
+1 bump, kindly request up-to-date kernel sources for the 6/6t

**Comment by Azal-Amer** [comment]
+1 bump, we need the updated sauce to pour over our fajitas and enchiladas, the old one started rotting.

**Comment by Claymore1297** [comment]
Guys, this is not Facebook. And OP is  compliing GPL, see https://www.gnu.org/licenses/gpl-faq.en.html#GPLRequireSourcePostedPublic . Anyway,it would be nice to have the sources, if there has been a change in kernel or just the info about this.

**Comment by ghost** [comment]
> Guys, this is not Facebook. And OP is compliing GPL, see https://www.gnu.org/licenses/gpl-faq.en.html#GPLRequireSourcePostedPublic . Anyway,it would be nice to have the sources, if there has been a change in kernel or just the info about this.

"But if you release the modified version to the public in some way, the GPL requires you to make the modified source code available to the program's users, under the GPL."

**Comment by ppajda** [comment]
+1 updated sauce

**Comment by Claymore1297** [comment]
Program's user are customers not the public,or at least that's what I understood. Well a reaction of OP would be nice...

**Comment by Desouler** [comment]
+1 to release the sources

**Comment by wget** [comment]
Dear Oneplus, I urge you to do the necessary to fix this situation!

**Comment by iAjayIND** [comment]
OnePlus is just getting shameless each passing day. Stop being a stubborn and release the kernel sources already

**Comment by sharkie63** [comment]
+1

**Comment by rnayabed** [comment]
Its pretty funny to see people even expecting a chinese tech company to respect GPL or any other opensource license. Huawei, an even bigger company just stole entire AOSP, replaced all mentions of Android with harmonyos, and claim they made it themselves from scratch. 🤡🤡🤡🤡

**Comment by erezgur** [comment]
+1 for this request!

**Comment by dpurnam** [comment]
+1, we want the 11.1.2.2 sources

**Comment by SevralT** [comment]
100% that they'll just ignore it....

**Comment by mcdachpappe** [comment]
Thank you for pushing the sources.
